name: Trigger auto deployment for flaskcobolapi

on:
  push:
    branches: 
      [ main ]
    paths:
      - '**'
      - '.github/workflows/flaskcobolapi-AutoDeployTrigger-d4fbd9f8-95b7-415b-87ec-a25d4783bf9d.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FLASKCOBOLAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FLASKCOBOLAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FLASKCOBOLAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy to Azure Container Apps (no ACR)
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          containerAppName: flaskcobolapi
          resourceGroup: flask-api-grupo
          dockerfilePath: Dockerfile
